spring.application.name=config-server

# ------------------------------
# SERVER (Render dynamic port)
# ------------------------------
server.port=${PORT:8888}



# ------------------------------
# CONFIG SERVER GIT REPO
# ------------------------------
spring.cloud.config.server.git.uri=${GIT_REPO_URI}
spring.cloud.config.server.git.username=${GIT_USERNAME}
spring.cloud.config.server.git.password=${GIT_PASSWORD}
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
